"""
Taxonomia de monitoramento político municipal para Belém.

Este módulo centraliza termos de alta precisão, órgãos, programas, riscos,
serviços, geografia local e exclusões. A intenção é alimentar tanto a query do
V-Tracker quanto filtros locais baratos antes da LLM.
"""

CORE_IDENTITY = {
    "prefeitura",
    "prefeito",
    "igor normando",
    "igor wander centeno normando",
    "prefeito igor",
    "prefeito de belém",
    "prefeito de belem",
    "prefeitura de belém",
    "prefeitura de belem",
    "prefeitura municipal de belém",
    "prefeitura municipal de belem",
    "pmb belém",
    "pmb belem",
    "palácio antônio lemos",
    "palacio antonio lemos",
    "cássio andrade",
    "cassio andrade",
    "cássio coelho andrade",
    "cassio coelho andrade",
    "vice-prefeito de belém",
    "vice-prefeito de belem",
    "gabinete do prefeito",
    "gabinete do vice-prefeito",
    "agência belém",
    "agencia belem",
}

GEO_QUALIFIERS = {
    "belém-pa",
    "belem-pa",
    "belém pa",
    "belem pa",
    "belém do pará",
    "belem do para",
    "capital paraense",
    "município de belém",
    "municipio de belem",
    "cidade de belém",
    "cidade de belem",
}

POLITICAL_CONTEXT = {
    "mdb",
    "psdb",
    "psb",
    "levanta belém",
    "levanta belem",
    "governo do pará",
    "governo do para",
    "helder barbalho",
    "câmara municipal de belém",
    "camara municipal de belem",
    "cmb",
    "john wayne",
    "vereadores de belém",
    "vereadores de belem",
    "base aliada",
    "oposição",
    "oposicao",
    "líder do governo",
    "lider do governo",
}

AGENCIES = {
    "arbel",
    "agência reguladora municipal de belém",
    "agencia reguladora municipal de belem",
    "belém digital",
    "belem digital",
    "companhia de transformação digital do município de belém",
    "companhia de transformacao digital do municipio de belem",
    "belemprev",
    "previdência do município de belém",
    "previdencia do municipio de belem",
    "cgm",
    "controladoria geral do município",
    "controladoria geral do municipio",
    "codem",
    "companhia de desenvolvimento e administração da área metropolitana de belém",
    "companhia de desenvolvimento e administracao da area metropolitana de belem",
    "funpapa",
    "fundação papa joão xxiii",
    "fundacao papa joao xxiii",
    "gmb",
    "guarda municipal de belém",
    "guarda municipal de belem",
    "iasb",
    "instituto de assistência à saúde dos servidores públicos do município de belém",
    "instituto de assistencia a saude dos servidores publicos do municipio de belem",
    "junta militar",
    "ogm",
    "ouvidoria geral do município de belém",
    "ouvidoria geral do municipio de belem",
    "pgm",
    "procuradoria geral do município",
    "procuradoria geral do municipio",
    "promaben",
    "programa de saneamento da bacia da estrada nova",
    "seame",
    "secretaria executiva segurança alimentar",
    "secretaria executiva seguranca alimentar",
    "seape",
    "secretaria municipal de agricultura e pesca",
    "secom",
    "secretaria municipal de comunicação",
    "secretaria municipal de comunicacao",
    "sect",
    "secretaria municipal de ciência e tecnologia",
    "secretaria municipal de ciencia e tecnologia",
    "secult",
    "secretaria municipal de cultura",
    "sedcon",
    "secretaria municipal de desenvolvimento econômico",
    "secretaria municipal de desenvolvimento economico",
    "sefin",
    "secretaria municipal de finanças",
    "secretaria municipal de financas",
    "segbel",
    "secretaria municipal de segurança, ordem pública e mobilidade de belém",
    "secretaria municipal de seguranca ordem publica e mobilidade de belem",
    "segep",
    "secretaria municipal de coordenação geral do planejamento e gestão",
    "secretaria municipal de coordenacao geral do planejamento e gestao",
    "segov",
    "secretaria municipal de governo",
    "sehab",
    "secretaria municipal de habitação",
    "secretaria municipal de habitacao",
    "seinfra",
    "secretaria municipal de obras e infraestrutura",
    "semcad",
    "secretaria municipal de cidadania assistência social e direitos humanos",
    "secretaria municipal de cidadania assistencia social e direitos humanos",
    "semec",
    "secretaria municipal de educação",
    "secretaria municipal de educacao",
    "semel",
    "secretaria municipal de esporte e lazer",
    "semiac",
    "secretaria municipal de inclusão e acessibilidade",
    "secretaria municipal de inclusao e acessibilidade",
    "semma",
    "secretaria municipal de meio ambiente",
    "semte",
    "secretaria municipal de trabalho e emprego",
    "semu",
    "secretaria municipal de mulher",
    "seopdec",
    "secretaria executiva de ordem pública e defesa civil",
    "secretaria executiva de ordem publica e defesa civil",
    "sepda",
    "secretaria municipal de proteção e defesa animal",
    "secretaria municipal de protecao e defesa animal",
    "sesma",
    "secretaria municipal de saúde",
    "secretaria municipal de saude",
    "setur",
    "secretaria municipal de turismo",
    "sezel",
    "secretaria municipal de zeladoria e conservação urbana",
    "secretaria municipal de zeladoria e conservacao urbana",
    "subprefeitura de icoaraci",
    "subprefeitura de mosqueiro",
    "subprefeitura de outeiro",
}

SECRETARIAT_NAMES = {
    "ana carolina gluck paul",
    "andré cunha",
    "andre cunha",
    "ariela motizuki",
    "arthur houat nery de souza",
    "cilene sabino",
    "cleidson chaves",
    "elen melo",
    "elizabete pires",
    "emanuel messias",
    "euler sizo",
    "glebson cavalcante",
    "gleisson oliveira",
    "gustavo costa",
    "gustavo bezerra da costa",
    "humberto bozi spindola",
    "luciano oliveira",
    "maycon pantoja",
    "nay barbalho",
    "patrick tranjan",
    "ricardo carneiro",
    "rômulo nina de azevedo",
    "romulo nina de azevedo",
    "silvane ferraz",
    "talita magalhães",
    "talita magalhaes",
    "thayta martins ferreira",
    "raphaela segadilha",
    "ricardo coelho brandão",
    "ricardo coelho brandao",
    "orlando reis pantoja",
    "mariel dacier lobato martin de mello",
    "edna gomes da silva",
    "esaú da cunha araújo",
    "esau da cunha araujo",
}

PROGRAMS_AND_DELIVERIES = {
    "cop30",
    "cop 30",
    "legado da cop30",
    "belém cop30",
    "belem cop30",
    "100 dias",
    "reforma administrativa",
    "arrumar a casa",
    "modernização dos serviços públicos",
    "modernizacao dos servicos publicos",
    "inclusão digital",
    "inclusao digital",
    "enfrentamento aos alagamentos",
    "belém limpa",
    "belem limpa",
    "coleta programada de entulho",
    "mutirão de limpeza",
    "mutirao de limpeza",
    "limpeza dos canais",
    "saneamento básico",
    "saneamento basico",
    "macrodrenagem",
    "macrodrenagem do mata fome",
    "mata fome",
    "asfaltamento",
    "600 ruas",
    "pavimentação",
    "pavimentacao",
    "tapa-buraco",
    "praça da cidadania",
    "praca da cidadania",
    "relatório anual de gestão",
    "relatorio anual de gestao",
    "rag 2025",
    "obras paralisadas",
    "dívidas com fornecedores",
    "dividas com fornecedores",
    "contratos desorganizados",
    "obras pagas e não executadas",
    "obras pagas e nao executadas",
}

MUNICIPAL_SERVICES = {
    "iptu",
    "itbi",
    "iss",
    "tlpl",
    "nota fiscal",
    "processo eletrônico",
    "processo eletronico",
    "agendamento eletrônico",
    "agendamento eletronico",
    "parcelamento de tributos",
    "pagamento de tributos",
    "coleta de lixo",
    "coleta de entulho",
    "iluminação pública",
    "iluminacao publica",
    "boca de lobo",
    "buraco",
    "asfalto",
    "alagamento",
    "canal",
    "esgoto",
    "ônibus",
    "onibus",
    "tarifa",
    "trânsito",
    "transito",
    "ambulantes",
    "feira",
    "mercado municipal",
    "posto de saúde",
    "posto de saude",
    "upa",
    "ubs",
    "medicamento",
    "fila",
    "consulta",
    "exame",
    "escola municipal",
    "creche",
    "matrícula",
    "matricula",
    "merenda",
    "transporte escolar",
    "professor",
    "servidor municipal",
    "concurso",
    "convocação",
    "convocacao",
    "greve",
    "paralisação",
    "paralisacao",
}

RISK_TERMS = {
    "denúncia",
    "denuncia",
    "investigação",
    "investigacao",
    "irregularidade",
    "ação civil pública",
    "acao civil publica",
    "ministério público",
    "ministerio publico",
    "mppa",
    "mpe",
    "tcm",
    "tcm-pa",
    "tce",
    "tce-pa",
    "tcu",
    "cgu",
    "tribunal de contas",
    "recomendação",
    "recomendacao",
    "inquérito civil",
    "inquerito civil",
    "auditoria",
    "fiscalização",
    "fiscalizacao",
    "improbidade",
    "licitação",
    "licitacao",
    "pregão",
    "pregao",
    "edital",
    "contrato",
    "termo aditivo",
    "dispensa de licitação",
    "dispensa de licitacao",
    "inexigibilidade",
    "ata de registro de preços",
    "ata de registro de precos",
    "chamamento público",
    "chamamento publico",
    "convênio",
    "convenio",
    "emenda parlamentar",
    "fornecedor",
    "terceirizada",
    "pagamento atrasado",
    "dívida",
    "divida",
    "restos a pagar",
    "falta de pagamento",
}

LOCAL_GEOGRAPHY = {
    "damos", "mosqueiro", "daout", "outeiro", "daico", "icoaraci", "daben", "benguí", "bengui",
    "daent", "entroncamento", "dasac", "sacramenta", "dabel", "dagua", "guamá", "guama",
    "jurunas", "terra firme", "montese", "condor", "cremação", "cremacao", "canudos",
    "pedreira", "telégrafo", "telegrafo", "barreiro", "fátima", "fatima", "maracangalha",
    "marco", "nazaré", "nazare", "umarizal", "batista campos", "cidade velha", "campina",
    "reduto", "são brás", "sao bras", "marambaia", "val-de-cans", "val de cans", "mangueirão",
    "mangueirao", "castanheira", "águas lindas", "aguas lindas", "aurá", "aura", "curió-utinga",
    "curio-utinga", "souza", "universitário", "universitario", "tapanã", "tapana", "cabanagem",
    "coqueiro", "parque verde", "pratinha", "una", "águas negras", "aguas negras", "agulha",
    "campina de icoaraci", "cruzeiro", "maracacueira", "paracuri", "parque guajará", "parque guajara",
    "ponta grossa", "tenoné", "tenone", "água boa", "agua boa", "brasília", "brasilia",
    "itaiteua", "são joão do outeiro", "sao joao do outeiro", "cotijuba", "combu",
}

NEGATIVE_EXCLUSIONS = {
    "belém-pb",
    "belem-pb",
    "belém pb",
    "belem pb",
    "prefeitura municipal de belém - pb",
    "prefeitura municipal de belem - pb",
    "belém/al",
    "belem/al",
    "belém al",
    "belem al",
    "belém de maria",
    "belem de maria",
    "belém do brejo do cruz",
    "belem do brejo do cruz",
    "belém de são francisco",
    "belem de sao francisco",
    "belém do são francisco",
    "belem do sao francisco",
    "belém palestina",
    "belem palestina",
    "belém portugal",
    "belem portugal",
    "bairro do belém",
    "bairro do belem",
    "estação belém",
    "estacao belem",
    "metrô belém",
    "metro belem",
    "são paulo belém",
    "sao paulo belem",
    "conquista normanda",
    "povo normando",
    "arquitetura normanda",
    "fafá de belém",
    "fafa de belem",
    "bethlehem",
}

LOW_PRIORITY_EXCLUSIONS = {
    "sorteio",
    "cupom",
    "promoção",
    "promocao",
    "link na bio",
    "bet",
    "aposta",
    "apostas",
    "brega",
    "viral",
    "apostila",
}

FOOTBALL_TERMS = {"remo", "paysandu", "papão", "papao", "leão azul", "leao azul"}

STRONG_MUNICIPAL_SIGNALS = (
    CORE_IDENTITY
    | AGENCIES
    | PROGRAMS_AND_DELIVERIES
    | MUNICIPAL_SERVICES
    | RISK_TERMS
    | POLITICAL_CONTEXT
)

WEAK_LOCAL_SIGNAL_TERMS = LOCAL_GEOGRAPHY | MUNICIPAL_SERVICES
